# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7742405f4665bd39feac6631b1d88ead4bd94ad88c05a5454ba15634d9d44f1133cc6a0225c8a67df2310fafbeada16f57b4cf17330228e008993daa9398842b

test:
  secret_key_base: b3a51d96f8f6205a629649014a16b8039dfbc6bac8e6e1e3578f1ed7e234eec5cdcbf9df5d31a8f405a045bbe52ecee9bbfc9bc715cc68a85da65a037803f953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
